Repository krokowski0x/Wasmo, pull requests merged in 2019-04, with the labels that each got.

#12 WASMO-11 Basic API with CRUD operations on users
  .gitignore
  db/index.js
  package-lock.json
  package.json
  server/handlers/user.js
  server/server.js
Labels: enhancement, ready for review

#10 Added responsive navbar
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/NavBar.js
  src/NavItems.js
  src/Navbar.scss
  src/favicon.ico
  src/index.js
  src/index.scss
Labels: enhancement, ready for review

#13 Added basic database model
  db/WasmoDatabaseModel.pdf
  db/WasmoDatabaseModel.sql
Labels: documentation, project setup

#15 Mkinas develop
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/App.scss
  src/App.test.js
  src/components/Auth/Auth.js
  src/components/LoginPage/Login.js
  src/components/LoginPage/Login.scss
  src/components/MainPage/MainPage.js
  src/components/MainPage/MainPage.scss
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavItems.js
  src/components/NavBar/Navbar.scss
  src/history.js
  src/images/facebook.png
  src/images/g+.png
  src/images/github.png
  src/images/login_bg.png
  src/index.css
  src/index.js
  src/index.scss
  src/routes.js
  src/scss/_wasmoHelpers.scss
Labels: enhancement, ready for review

#24 WASMO-17 Demo #1
  src/components/Dashboard/Dashboard.js
  src/components/Game/Comments.js
  src/components/Game/Game.js
  src/components/Game/seed_comments.js
  src/components/NavBar/NavItems.js
  src/components/Settings/Settings.js
  src/components/Upload/Upload.js
  src/components/User/UserDashboard.js
  src/routes.js
Labels: enhancement, project setup
